version: "3.3"

services:
  demodb:
    build: ./demodb
    container_name: postgres_basic.demodb
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    restart: always

  notebook:
    build: ./gophernotes
    container_name: postgres_basic.gophernotes
    ports:
      - 8888:8888
    volumes:
      - /vagrant/practices:/home/jovyan/notebooks
      - /vagrant/utils:/home/jovyan/utils
      - /vagrant/utilsgo:/home/jovyan/utilsgo
    restart: always
